// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpx1QefsbywCz0YsgiPKVF2NmLhbvXEVs',
    appId: '1:853962716562:web:87ef94956edc45e7337d4b',
    messagingSenderId: '853962716562',
    projectId: 'chatapp-3cf10',
    authDomain: 'chatapp-3cf10.firebaseapp.com',
    storageBucket: 'chatapp-3cf10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLHHFroEbvDagVLY9Vnk7FHrx1CC85_U',
    appId: '1:853962716562:android:7d14fb26086f15c1337d4b',
    messagingSenderId: '853962716562',
    projectId: 'chatapp-3cf10',
    storageBucket: 'chatapp-3cf10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJ0p-ItDeqpkabMnDEhDFZu2Ua_kh8Uw',
    appId: '1:853962716562:ios:390d3cf73bf30c24337d4b',
    messagingSenderId: '853962716562',
    projectId: 'chatapp-3cf10',
    storageBucket: 'chatapp-3cf10.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJ0p-ItDeqpkabMnDEhDFZu2Ua_kh8Uw',
    appId: '1:853962716562:ios:390d3cf73bf30c24337d4b',
    messagingSenderId: '853962716562',
    projectId: 'chatapp-3cf10',
    storageBucket: 'chatapp-3cf10.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpx1QefsbywCz0YsgiPKVF2NmLhbvXEVs',
    appId: '1:853962716562:web:e00822d49a641d9a337d4b',
    messagingSenderId: '853962716562',
    projectId: 'chatapp-3cf10',
    authDomain: 'chatapp-3cf10.firebaseapp.com',
    storageBucket: 'chatapp-3cf10.appspot.com',
  );
}
